name: "Setup CSharp"
description: "Install csharp, get student code and test code."
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: bth-algo/template2

    - uses: actions/checkout@v4
      with:
        path: ./student-submission

    - name: Copy test code to student code
      shell: bash
      run: |
        rsync -av --delete ./student-submission/kmom* .

    - name: "Set up .NET SDK and CSharp"
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Debug context
      shell: bash
      run: |
        echo "github.ref: ${{ github.ref }}"
        echo "github.head_ref: ${{ github.head_ref }}"
        echo "github.base_ref: ${{ github.base_ref }}"
        echo "github.event_name: ${{ github.event_name }}"
        echo "github.event.repository.name: ${{ github.event.repository.name }}"
